package com.autocare.platform.file;

public interface PrivateObjectStore {
    /** Must verify the configured target denies anonymous access, never just infer from a name. */
    boolean isPrivate();
    /** A failure may leave an object. The key is always generated by the application. */
    void put(String key, String contentType, byte[] bytes);
    /** Idempotent, succeeds if the object is already absent; adapters must enforce timeouts. */
    void delete(String key);
}
