-- V007: repeatable, preserving existing order and slot history.
SET @reservation_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='appointment_slot' AND column_name='is_open')=0, 'ALTER TABLE `appointment_slot` ADD COLUMN `is_open` TINYINT NOT NULL DEFAULT 1', 'SELECT 1');
PREPARE reservation_statement FROM @reservation_ddl;
EXECUTE reservation_statement;
DEALLOCATE PREPARE reservation_statement;
SET @reservation_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='appointment_slot' AND column_name='closed_at')=0, 'ALTER TABLE `appointment_slot` ADD COLUMN `closed_at` DATETIME DEFAULT NULL', 'SELECT 1');
PREPARE reservation_statement FROM @reservation_ddl;
EXECUTE reservation_statement;
DEALLOCATE PREPARE reservation_statement;
SET @reservation_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='order' AND column_name='merchant_project_id')=0, 'ALTER TABLE `order` ADD COLUMN `merchant_project_id` BIGINT UNSIGNED DEFAULT NULL', 'SELECT 1');
PREPARE reservation_statement FROM @reservation_ddl;
EXECUTE reservation_statement;
DEALLOCATE PREPARE reservation_statement;
SET @reservation_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='order' AND column_name='quote_version_id')=0, 'ALTER TABLE `order` ADD COLUMN `quote_version_id` BIGINT UNSIGNED DEFAULT NULL', 'SELECT 1');
PREPARE reservation_statement FROM @reservation_ddl;
EXECUTE reservation_statement;
DEALLOCATE PREPARE reservation_statement;
SET @reservation_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='order' AND column_name='appointment_snapshot')=0, 'ALTER TABLE `order` ADD COLUMN `appointment_snapshot` JSON DEFAULT NULL', 'SELECT 1');
PREPARE reservation_statement FROM @reservation_ddl;
EXECUTE reservation_statement;
DEALLOCATE PREPARE reservation_statement;
SET @reservation_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='order' AND column_name='closed_at')=0, 'ALTER TABLE `order` ADD COLUMN `closed_at` DATETIME DEFAULT NULL', 'SELECT 1');
PREPARE reservation_statement FROM @reservation_ddl;
EXECUTE reservation_statement;
DEALLOCATE PREPARE reservation_statement;
SET @reservation_ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='order' AND column_name='close_reason')=0, 'ALTER TABLE `order` ADD COLUMN `close_reason` VARCHAR(32) DEFAULT NULL', 'SELECT 1');
PREPARE reservation_statement FROM @reservation_ddl;
EXECUTE reservation_statement;
DEALLOCATE PREPARE reservation_statement;
SET @reservation_ddl = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='order' AND index_name='idx_slot_status_expiry')=0, 'ALTER TABLE `order` ADD INDEX `idx_slot_status_expiry` (slot_id,status,expires_at)', 'SELECT 1');
PREPARE reservation_statement FROM @reservation_ddl;
EXECUTE reservation_statement;
DEALLOCATE PREPARE reservation_statement;
SET @reservation_ddl = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='order' AND index_name='idx_pending_expiry')=0, 'ALTER TABLE `order` ADD INDEX `idx_pending_expiry` (status,expires_at,id)', 'SELECT 1');
PREPARE reservation_statement FROM @reservation_ddl;
EXECUTE reservation_statement;
DEALLOCATE PREPARE reservation_statement;
SET @reservation_ddl = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='appointment_slot' AND index_name='idx_project_window')=0, 'ALTER TABLE `appointment_slot` ADD INDEX `idx_project_window` (merchant_id,project_id,starts_at,ends_at)', 'SELECT 1');
PREPARE reservation_statement FROM @reservation_ddl;
EXECUTE reservation_statement;
DEALLOCATE PREPARE reservation_statement;
