"""Build the repeatable S0 schema from the 16 source tables and extensions.

Run: python scripts/build_init_sql.py
"""

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs" / "reference" / "DELIVERY_V1.md"
EXTRA = ROOT / "docs/sql/extra_tables.sql"
OUTPUT = ROOT / "docs/sql/init.sql"
MIGRATION = ROOT / "docs/sql/migrations/V001__baseline.sql"


def main():
    source = SOURCE.read_text(encoding="utf-8")
    section = source.split("### 7.2 建表 SQL", 1)[1].split("### 7.3", 1)[0]
    match = re.search(r"```sql\s*(.*?)```", section, flags=re.S)
    if not match:
        raise ValueError("No source SQL block found")
    tables = re.findall(r"CREATE TABLE `([^`]+)` \(.*?\) ENGINE=InnoDB.*?;", match.group(1), re.S)
    statements = re.findall(r"CREATE TABLE `[^`]+` \(.*?\) ENGINE=InnoDB.*?;", match.group(1), re.S)
    if len(tables) != 16 or len(set(tables)) != 16:
        raise ValueError(f"Expected 16 distinct source tables; got {tables}")

    output = []
    for table, statement in zip(tables, statements):
        statement = statement.replace("CREATE TABLE `", "CREATE TABLE IF NOT EXISTS `", 1)
        if table == "merchant":
            statement = statement.replace("`commission_rate` DECIMAL(5,2) DEFAULT 3.00", "`commission_rate` DECIMAL(5,2) DEFAULT NULL")
        if table == "order":
            statement = re.sub(r"`status` TINYINT NOT NULL DEFAULT 0 COMMENT '[^']*'", "`status` VARCHAR(32) NOT NULL DEFAULT 'PENDING_PAYMENT'", statement)
            statement = statement.replace("  PRIMARY KEY (`id`),", "  `project_snapshot` JSON DEFAULT NULL,\n  `merchant_snapshot` JSON DEFAULT NULL,\n  `price_snapshot` JSON DEFAULT NULL,\n  `slot_id` BIGINT UNSIGNED DEFAULT NULL,\n  `expires_at` DATETIME DEFAULT NULL,\n  PRIMARY KEY (`id`),", 1)
        additions = []
        if "`created_at`" not in statement:
            additions.append("  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,")
        if "`updated_at`" not in statement:
            additions.append("  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,")
        if "`is_deleted`" not in statement:
            additions.append("  `is_deleted` TINYINT NOT NULL DEFAULT 0,")
        statement = statement.replace("  PRIMARY KEY (`id`),", "\n".join(additions) + ("\n" if additions else "") + "  PRIMARY KEY (`id`),", 1)
        output.append(statement)

    header = """-- S0 baseline schema, MySQL 8.0; generated by scripts/build_init_sql.py.
-- Run with a selected empty database. Re-running is safe for an unchanged schema.
-- Future changes belong in versioned migrations; CREATE IF NOT EXISTS does not alter existing tables.
SET NAMES utf8mb4;
"""
    content = header + "\n\n".join(output) + "\n\n" + EXTRA.read_text(encoding="utf-8")
    names = re.findall(r"CREATE TABLE IF NOT EXISTS `([^`]+)`", content)
    if len(names) != 39 or len(names) != len(set(names)):
        raise ValueError(f"Expected 39 distinct tables; got {len(names)}")
    for name in names:
        table = re.search(rf"CREATE TABLE IF NOT EXISTS `{name}` \(.*?\) ENGINE=InnoDB", content, re.S).group(0)
        for column in ("id", "created_at", "updated_at", "is_deleted"):
            if f"`{column}`" not in table:
                raise ValueError(f"{name} is missing {column}")
    OUTPUT.write_text(content, encoding="utf-8")
    MIGRATION.parent.mkdir(parents=True, exist_ok=True)
    MIGRATION.write_text(content, encoding="utf-8")
    print(f"Wrote {len(names)} tables to {OUTPUT.relative_to(ROOT)} and {MIGRATION.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
